Nmh issue3
TonePoems/PyRPG_Mini pull request #16
Opened 2020-04-16 17:18 UTC by nmhijazi15

This merges the caesar cipher game, the word scramble, and some input validation on the main menu

2020-04-16 17:49 UTC, caleb-austin requested changes
Fix the merge conflicts and then you should be good to go

2020-04-16 18:36 UTC, gbrown97 approved these changes

2020-04-16 19:03 UTC, TonePoems reviewed
One question, why did you modify the new game vs load game selection logic?

2020-04-21 18:57 UTC, caleb-austin approved these changes
Everything looks good to me now. The minigames seem like a nice addition

2020-04-21 19:54 UTC, TonePoems submitted a review, later dismissed

2020-04-21 19:57 UTC, merged